- name : Configure Docker on EC2 Instances
  hosts : webservers
  become: true
  connection : ssh
  tasks : 
  - name:  apt update
    command : sudo apt-get update

  - name : Install Docker
    command : sudo apt-get install -y docker.io

  - name : Start Docker Service
    command : sudo systemctl start docker

  - name: Deploy Docker Container
    command: docker run -itd -p 8086:8080 mchandana123/chandanabanking:1.0
